---
title: "ADH-s trial"
author: "TS O'Leary"
output:
  rmarkdown::html_document:
    theme: lumen
    toc: true
    toc_float: true
---

```{r setup, include = FALSE}
# Set up chunk defaults
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# Load packages
require(tidyverse)
require(broom)
require(RColorBrewer)
require(kableExtra)

# Source required functions
source(here::here("ADH/scripts/adh_batch_functions.R"))
```

# Reaction Velcocities

```{r}
# Read in data -----------------------------------------------------------------
data_s <- read_bind_tidy_csv(dir = here::here("ADH/data/trial")) %>%
  filter(file == "adh-s_trial_2_061120.csv") %>%
  filter(time <= 30)
```

## ADH-slow enzyme

```{r, fig.height = 7, fig.width = 10}
plot_velo(data_s)
```


```{r}
# Calculate reaction velocities at each [EtOH] and each Temp group -------------
data_velo_s <- calc_velocity(data_s)
data_velo_s %>%
  select(temp_group, conc, velocity, r.squared) %>%
  kable() %>%
  kable_styling("striped") %>%
  scroll_box(width = "100%", height = "100%")
```

# Fit Michaelis–Menten curves

## ADH-slow enzyme

```{r}
plot_mm_curve(data_velo_s, legend_labels = "23.5°C")
```

```{r}
# Determine the Km and Vmax from the fit of the Michaelis–Menten curves --------
data_Km_Vm_s <- calc_Km_Vm(data_velo_s)
data_Km_Vm_s %>% 
  select(term, estimate, std.error, r.squared)
```
