---
title: "ADH-s trial"
author: "TS O'Leary"
output:
  rmarkdown::html_document:
    theme: lumen
    toc: true
    toc_float: true
---

```{r setup, include = FALSE}
# Set up chunk defaults
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# Load packages
require(tidyverse)
require(broom)
require(RColorBrewer)
require(kableExtra)

# Source required functions
source(here::here("ADH/scripts/adh_batch_functions.R"))
```

# ADH Activity

```{r}
# Read in data -----------------------------------------------------------------
# Load and tidy data
setwd(here::here("ADH/data/biovision"))
nadh <- read_tidy_nadh_csv("NADH_std_10012020.csv")
abs <- read_tidy_adh_abs_csv("adh_abs_10012020.csv")
```

## Standard Curve

```{r, eval = FALSE}
# Plot the standard curve 
plot_std_curve(nadh)
```

```{r}
# Get the means of the NADH data
nadh_med <- nadh %>%
  group_by(NADH) %>%
  summarize(abs = median(abs))

# Plot the standard curve 
plot_std_curve(nadh_med)

# Get the slopes and intercepts of the standard curve
std_curve_lm <- std_curve(nadh_med)
```


```{r}
# Get specific ADH data.
abs_0_f <- abs %>%
  mutate(EtOH = as.factor(EtOH)) %>%
  group_by(EtOH, temp, sample_vol, n_flies, genotype, mins) %>%
  summarize(abs = median(abs)) %>%
  filter(mins %in% c(0, 60))

# Plot the absorbance over time
plot_sample_abs_time(abs_0_f)
```



```{r}
# Calculate ADH activity
t <- calc_adh_activity(abs_0_f, std_curve_lm, t_0 = 0)
```

# Fit Michaelis–Menten curves

## ADH-slow enzyme

```{r}
# Plot the MM Curve
plot_mm_curve_biovision(t %>%
                          filter(EtOH != 0))
```
```{r}
calc_Km_Vm_biovision(t)  %>%
  select(genotype, temp, term, estimate, std.error, r.squared) %>%
  pivot_wider(names_from = term, 
              values_from = c(estimate, std.error)) %>%
  select(genotype, temp, contains("Km"), r.squared) %>%
  mutate(`Km (± SEM)`= 
           paste0(round(estimate_Km, 2), " (± ", 
                  round(std.error_Km, 2), ")")) %>%
  select(genotype, temp, `Km (± SEM)`, r.squared) %>%
  arrange(genotype, temp,) %>%
  kable() %>%
  kable_styling("striped") %>%
  scroll_box(width = "100%", height = "100%")
```
